In [1]:
import numpy as np

Last lesson we have talked about creating n dimensional arrays: 
vectors, matricies and how to transpose them; Le's revise previous topic:

In [3]:
arr1=np.arange(12)
print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
12
(12,)


2 dimensional array=>Matrix

In [6]:
arr2=arr1.reshape(3,4)
print(arr2)
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12
(3, 4)


In [ ]:
arr3=arr2.T
print(arr3)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)

In [ ]:
arr4=np.arange(3*3*3).reshape(3,3,3)
print(arr4)
print(arr4.ndim)
print(arr4.size)
print(arr4.shape)
type(arr4)
print(arr4.dtype)

random function

In [ ]:
arr5=np.random.rand(2,2)   # returns ndim array consist of elems between[-1;1]
print(arr5)

In [ ]:
arr6=np.random.randn(3,4) # returns ndim array consist of elems obeying normal distribution
print(arr6)

Identity matrix

In [ ]:
arr7=np.identity(4)
print(arr7)

In [ ]:
arr8=np.eye(4,k=0)
print(arr8)

changing axis

In [ ]:
arr11=np.random.rand(3,3)
arr11

In [ ]:
print(arr11.swapaxes(0,1))
print(arr11.T)
#print(arr8.swapaxes(0,1))

sqrt; square;exp; log; modf: integer and fractional part; sign; add; multiply; maximum;

In [253]:
a1=np.arange(9).reshape(3,3)
a2=np.arange(10,19).reshape(3,3)

In [ ]:
print(a1)

In [ ]:
print(a2)

In [ ]:
np.sqrt(a1)

In [ ]:
np.square(a1)

In [ ]:
np.exp(a1)

In [ ]:
a1**3

In [ ]:
a3=np.random.randn(3,3)
print(a3)

In [ ]:
frac,int1=np.modf(a3)
print(int1)

In [ ]:
frac

In [ ]:
np.sign(a3)

In [272]:
a4=np.array([-3,-4.5,-3.3,4,5,6,7,8,-10,0])

In [ ]:
a4

In [ ]:
np.sign(a4)

In [ ]:
a1

In [280]:
a2=np.arange(3*3).reshape(3,3)
print(a2)

In [ ]:
np.multiply(a1,a2)

In [ ]:
a3=np.arange(1,11).reshape(1,10)
a3

In [ ]:
np.dot(a1,a2)

In [ ]:
np.dot(a3.T,a3)

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the cross product using np.cross
cross_product = np.cross(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Cross Product:", cross_product)

In [ ]:
np.dot(vector1,vector2)

In [289]:
a3=np.arange(1,16).reshape(3,5)

In [ ]:
a3

### array[row,column], indexing, slicing, sorting  


a3[:,2] #prints 2nd column

In [ ]:
a3[0,1]

In [ ]:
a3[0,:]

In [ ]:
a3[:2,:]

In [ ]:
a4=np.arange(3*3*3).reshape(3,3,3)
a4

In [ ]:
a4[0]

In [ ]:
a5=a4[0][2]
a5

In [ ]:
np.max(a5)

In [ ]:
a4[0][2][1]

In [191]:
#a4=np.random.randn(3,3)

In [200]:
#a4

In [199]:
#np.sort(a4,axis=1)

In [202]:
a5=np.array(["Alisher","Hasan","Husan","Hasan","Alisher"])

In [ ]:
np.unique(a5)